# Generated by Django 3.2.6 on 2021-11-04 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('products', '0001_initial'), ('products', '0002_product_size'), ('products', '0003_auto_20211030_1859'), ('products', '0004_alter_product_publish_date'), ('products', '0005_auto_20211101_2037'), ('products', '0006_auto_20211101_2101')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PatternImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('images', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.fabricimage')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('images', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.patternimage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(default='M', max_length=10)),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fabrics', models.ManyToManyField(to='products.Fabric')),
                ('images', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.productimage')),
                ('pattern', models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='products.pattern')),
            ],
        ),
    ]
