# Generated by Django 3.2.6 on 2021-10-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='M', max_length=10),
            preserve_default=False,
        ),
    ]
