# Generated by Django 3.2.6 on 2021-11-06 10:49

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='an', max_length=100, no_check_for_status=True),
        ),
    ]
