# Generated by Django 3.2.6 on 2021-10-30 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211030_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
