# Generated by Django 3.2.6 on 2021-11-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='product',
        ),
        migrations.AddField(
            model_name='fabric',
            name='product',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pattern',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
