# Generated by Django 3.2.6 on 2021-11-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211101_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='product',
        ),
        migrations.RemoveField(
            model_name='fabricimage',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='product',
        ),
        migrations.RemoveField(
            model_name='patternimage',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='fabric',
            name='images',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.fabricimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='images',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.patternimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(to='products.Fabric'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='products.pattern'),
            preserve_default=False,
        ),
    ]
